name: test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.38.0

      - name: Check format
        run: deno fmt --check
      - name: Run lint
        run: deno lint
      - name: Incompatible Deno version
        run: deno run mod.ts

